DROP SCHEMA IF EXISTS juegos_olimpicos;
CREATE SCHEMA juegos_olimpicos;
USE juegos_olimpicos;

-- TABLA PAIS
CREATE TABLE PAIS (
	nombre_pais VARCHAR(50) NOT NULL,
    numpart SMALLINT UNSIGNED NOT NULL,
    nummed SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (nombre_pais)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA DEPORTISTA
CREATE TABLE DEPORTISTA (
	matricula VARCHAR(20) NOT NULL,
    nombre_dep VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    sexo VARCHAR(10) NOT NULL,
    pais VARCHAR(50) NOT NULL,
    puntos SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (matricula),
    CONSTRAINT `fk_DEPORTISTA_PAIS` FOREIGN KEY (pais) REFERENCES PAIS(nombre_pais) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA DISCIPLINA
CREATE TABLE DISCIPLINA (
	identificador VARCHAR(20) NOT NULL, 
    nombre_dis VARCHAR(50) NOT NULL, 
    gloabaldisciplina VARCHAR(50) NOT NULL,
    puntos SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (identificador)
)DEFAULT CHARSET=utf8mb4;

-- TABLA PRUEBA
CREATE TABLE PRUEBA (
	identificador VARCHAR(20) NOT NULL,
	disciplina VARCHAR(20) NOT NULL,
	fecha DATETIME NOT NULL,
	lugar VARCHAR(50) NOT NULL,
	numdep INT NOT NULL,
	naturaleza VARCHAR(30) NOT NULL,
	PRIMARY KEY (identificador),
	CONSTRAINT `fk_PRUEBA_DISCIPLINA` FOREIGN KEY (disciplina) REFERENCES DISCIPLINA(identificador) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA CLASIFICACION
CREATE TABLE CLASIFICACION (
	identificador SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT, 
    deportista VARCHAR(20) NOT NULL, 
    prueba VARCHAR(20) NOT NULL,
    rango SMALLINT UNSIGNED NOT NULL, 
    PRIMARY KEY (identificador),
    CONSTRAINT `fk_CLASIFICACION_DEPORTISTA` FOREIGN KEY (deportista) REFERENCES DEPORTISTA(matricula) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_CLASIFICACION_PRUEBA` FOREIGN KEY (prueba) REFERENCES PRUEBA(identificador) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA RESULTADO
CREATE TABLE RESULTADO (
	disciplina VARCHAR(20) NOT NULL,
    mdoro VARCHAR(20) NOT NULL, 
    mdplata VARCHAR(20) NOT NULL, 
    mdbronce VARCHAR(20) NOT NULL, 
    PRIMARY KEY (disciplina), 
    CONSTRAINT `fk_RESULTADO_PAIS` FOREIGN KEY (disciplina) REFERENCES DISCIPLINA(identificador) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk1_RESULTADO_DEPORTISTA` FOREIGN KEY (mdoro) REFERENCES DEPORTISTA(matricula) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk2_DRESULTADO_DEPORTISTA` FOREIGN KEY (mdplata) REFERENCES DEPORTISTA(matricula) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk3_RESULTADO_DEPORTISTA` FOREIGN KEY (mdbronce) REFERENCES DEPORTISTA(matricula) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

